# Generated by Django 3.1.6 on 2021-02-06 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210206_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='productid',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='userid',
        ),
    ]
